[package]
name = "shadows-of-the-knight-episode-1"
version = "0.1.0"
edition = "2021"
description = "https://www.codingame.com/ide/puzzle/shadows-of-the-knight-episode-1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
