[package]
name = "logic_gates"
version = "0.1.0"
edition = "2021"
description = "Solving logic gate from codingame."
documentation = "https://www.codingame.com/ide/puzzle/logic-gates"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
