[package]
name = "chuck_norris"
version = "0.1.0"
authors = ["gthvn0 <gthvn0@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
